---
- name: get credential
  hosts: all
  tasks:
  - name: credential retrieval basic
    cyberark.pas.cyberark_credential:
        api_base_url: "{{ aim_base_url }}"
        app_id: "{{ aim_base_app_id }}"
        query: "{{ aim_base_query }}"
        validate_certs: "{{ aim_validate_certs | default (false) }}"
    register: result

  block:
    - wait: 10
    - name: credential retrieval basic
      cyberark.pas.cyberark_credential:
        api_base_url: "{{ aim_base_url }}"
        app_id: "{{ aim_base_app_id }}"
        query: "{{ aim_base_query }}"
        validate_certs: "{{ aim_validate_certs | default (false) }}"
    register: result
    when: result.PasswordChangeInProcess == True
    
  - debug:
      var: result.Content
