---
- name: get credential
  hosts: all
  tasks:
  - name: credential retrieval basic
    cyberark_credential:
        api_base_url: "{{ aim_base_url }}"
        app_id: "{{ aim_base_app_id }}"
        query: "{{ aim_base_query }}"
    register: result
    
  - debug:
      var: result
